name: Publish Container Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version tag format
        run: |
          if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "Tag must match vX.Y (for example v1.2)"
            exit 1
          fi

      - name: Build image
        run: |
          IMAGE_NAME=${{ github.repository }}
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_NAME=${{ github.repository }}
          IMAGE_ID=ghcr.io/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          REF=${{ github.ref }}
          VERSION=$(echo "$REF" | sed -e 's,.*/,,') # extract last part

          VERSION=$(echo $VERSION | sed -e 's/^v//')  # strip 'v' prefix

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          # Tag and push the full minor version.
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          # Split version into major and minor components.
          IFS='.' read -r MAJOR MINOR <<< "$VERSION"

          TAGS=("$MAJOR" "$MAJOR.$MINOR")

          for TAG in "${TAGS[@]}"; do
            echo "Tagging $IMAGE_ID:$TAG"
            docker tag $IMAGE_NAME $IMAGE_ID:$TAG
            docker push $IMAGE_ID:$TAG
          done

          echo "Tagging $IMAGE_ID:latest"
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest